### ISSUE TITLE
is this mod better than particle core?

### ISSUE THREAD

**Issue by ImYosu** [elijahjibben/CullParticlesFabric#1]

**Comment by elijahjibben** [comment]
In most circumstances, no. Particle Core's most important function is to cull particles, which is exactly what this mod does. The majority of the fps increase/cpu usage reduction is from this. Particle Core also does some other optimizations that can sometimes be messy or annoying particularly on servers. This mod is essentially lightweight and highly compatible so if particle core works for your application, great! If not, try this mod instead.
